### ISSUE TITLE
[Dev] ignore `pytest.PytestDeprecationWarning` in tests

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#1295]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
- [X] I have confirmed I will follow and update [contribution guideline](https://lisphilar.github.io/covid19-sir/CONTRIBUTING.html).

### Issues of the current workflow

`pytest` version 7.2.0 raises `pytest.PytestDeprecationWarning` and this is ignoreable.

### Action items

Replace
```toml
[tool.pytest.ini_options]
filterwarnings = ["error"]
```
with
```toml
[tool.pytest.ini_options]
filterwarnings = ["error", "ignore::pytest.PytestDeprecationWarning"]
```
in pyproject.toml file.
